# Generated by Django 2.2.6 on 2019-10-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_answer_is_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Тест'),
        ),
    ]
