# Generated by Django 2.2.7 on 2019-11-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191106_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название теста'),
        ),
    ]
